"""Create User model

Revision ID: aa701786b9b8
Revises: 7b34db627f19
Create Date: 2025-07-03 11:16:10.490122

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = 'aa701786b9b8'
down_revision: Union[str, Sequence[str], None] = '7b34db627f19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
