[project]
name = "e-store"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi-slim>=0.115.14",
    "sqlalchemy>=2.0.41",
    "uvicorn>=0.34.3",
]
